- name: WSL dotfiles
  hosts: localhost
  vars:
    dotfiles: "git --git-dir={{ ansible_env.HOME }}/.dotfiles.git --work-tree={{ ansible_env.HOME }}"
  vars_files:
    - vault.yml

  tasks:
    - name: Clone the yay repository
      ansible.builtin.git:
        repo: https://aur.archlinux.org/yay.git
        dest: "{{ playbook_dir }}/yay"
        version: master
        clone: true
        update: true
      notify: Build yay

    - name: Install packages with yay
      community.general.pacman:
        name: 
          - bat
          - eza
          - git
          - github-cli
          - less
          - man-db
          - neovim
          - npm
          - openssh
          - python-pynvim
          - ripgrep
          - rustup
          - starship
          - unzip
          - zoxide
        state: latest
        update_cache: true
        executable: yay

    - name: Setup rustup 
      command: "rustup default stable"

    - name: Install packages with cargo
      community.general.cargo:
        name: tree-sitter-cli
        state: latest

    - name: Set git credentials
      command: "{{ item }}"
      loop:
        - git config --global user.name ferriccc
        - git config --global user.email shrey.260904@gmail.com

    - name: Clone dotfiles repository as a bare repo
      ansible.builtin.git:
        repo: "https://x-access-token:{{ github_token }}@github.com/Ferriccc/dotfiles"
        dest: "{{ ansible_env.HOME }}/.dotfiles.git"
        version: main
        bare: true
        update: true
      notify: Checkout dotfiles

    - name: Configure bare dotfiles repo to only show tracked file
      command: "{{ item }}"
      loop:
        - "dotfiles config --local status.showUntrackedFiles no"

    - name: Automatically push tracked files to remote
      command: "dotfiles add {{ ansible_env.HOME }}/{{ item }}"
      loop:
        - ".bashrc"
        - "scripts/"
        - ".config/nvim/"
      notify: Commit changes
      tags: push

  handlers:
    - name: Build yay
      command: makepkg -si --noconfirm
      args:
        chdir: "{{ playbook_dir }}/yay"

    - name: Checkout dotfiles
      command: "{{ item }}"
      loop:
        - "dotfiles checkout"
        - "dotfiles fetch --all"
        - "dotfiles reset --hard"

    - name: Commit changes
      command: "dotfiles commit -m \"automated commit using playbook\" && dotfiles push origin main"
      ignore_errors: true
